In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv('DATA /Churn_Modelling.csv')

In [3]:
data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

## Data Preprocessing

In [4]:
data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [5]:
X = data.iloc[:,3:13].values
y = data.iloc[:,-1].values

In [6]:
X , y

(array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
        [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
        [502, 'France', 'Female', ..., 1, 0, 113931.57],
        ...,
        [709, 'France', 'Female', ..., 0, 1, 42085.58],
        [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
        [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object),
 array([1, 0, 1, ..., 1, 1, 0]))

### Handle Categorical Data

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder_X_1 = LabelEncoder()
X[:,1] = labelencoder_X_1.fit_transform(X[:,1])

labelencoder_X_2 = LabelEncoder()
X[:,2] = labelencoder_X_2.fit_transform(X[:,2])

X[0]

array([619, 0, 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [8]:
from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer([("Onehot",OneHotEncoder(),[1])],remainder = "passthrough")
X = transformer.fit_transform(X)

X[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [9]:
X[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [10]:
X = X[:,1:]

In [11]:
X[0]

array([0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [12]:
X.shape

(10000, 11)

## Split the data 

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state=0)

In [14]:
len(X_train) , len(X_test) , len(y_train) , len(y_test)

(8000, 2000, 8000, 2000)

In [15]:
X_train

array([[0.0, 1.0, 667, ..., 1, 0, 163830.64],
       [1.0, 0.0, 427, ..., 1, 1, 57098.0],
       [0.0, 0.0, 535, ..., 1, 0, 185630.76],
       ...,
       [0.0, 0.0, 738, ..., 1, 0, 181429.87],
       [0.0, 1.0, 590, ..., 1, 1, 148750.16],
       [1.0, 0.0, 623, ..., 1, 0, 118855.26]], dtype=object)

## Feature Scaling

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Artificial Neural Netwrok

In [17]:
import keras
from keras.models import Sequential
from keras.layers import Dense

### Initialising the ANN

In [18]:
classifier = Sequential()

# Add Input layer and first hidden layer
classifier.add(Dense(6,activation='relu',kernel_initializer='glorot_uniform',input_dim=11))

# Add second hidden layer
classifier.add(Dense(6,activation='relu',kernel_initializer='glorot_uniform'))

# Add the output Layer
classifier.add(Dense(1,activation='sigmoid',kernel_initializer='glorot_uniform'))

# Compile the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics=['accuracy'])

### Fit ANN to training set

In [19]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 0s 535us/step - loss: 0.4834 - accuracy: 0.7960
Epoch 2/100
800/800 [==============================] - 0s 496us/step - loss: 0.4385 - accuracy: 0.8024
Epoch 3/100
800/800 [==============================] - 0s 504us/step - loss: 0.4272 - accuracy: 0.8127
Epoch 4/100
800/800 [==============================] - 0s 453us/step - loss: 0.4198 - accuracy: 0.8163
Epoch 5/100
800/800 [==============================] - 0s 463us/step - loss: 0.4134 - accuracy: 0.8227
Epoch 6/100
800/800 [==============================] - 0s 453us/step - loss: 0.4044 - accuracy: 0.8305
Epoch 7/100
800/800 [==============================] - 0s 449us/step - loss: 0.3922 - accuracy: 0.8359
Epoch 8/100
800/800 [==============================] - 0s 453us/step - loss: 0.3768 - accuracy: 0.8446
Epoch 9/100
800/800 [==============================] - 0s 481us/step - loss: 0.3641 - accuracy: 0.8506
Epoch 10/100
800/800 [==============================] - 0s 451us/step - l

800/800 [==============================] - 0s 479us/step - loss: 0.3352 - accuracy: 0.8626
Epoch 80/100
800/800 [==============================] - 0s 487us/step - loss: 0.3352 - accuracy: 0.8636
Epoch 81/100
800/800 [==============================] - 0s 523us/step - loss: 0.3350 - accuracy: 0.8634
Epoch 82/100
800/800 [==============================] - 1s 699us/step - loss: 0.3347 - accuracy: 0.8636
Epoch 83/100
800/800 [==============================] - 1s 732us/step - loss: 0.3352 - accuracy: 0.8643
Epoch 84/100
800/800 [==============================] - 1s 783us/step - loss: 0.3353 - accuracy: 0.8633
Epoch 85/100
800/800 [==============================] - 1s 772us/step - loss: 0.3340 - accuracy: 0.8630
Epoch 86/100
800/800 [==============================] - 1s 753us/step - loss: 0.3352 - accuracy: 0.8616
Epoch 87/100
800/800 [==============================] - 1s 634us/step - loss: 0.3344 - accuracy: 0.8648
Epoch 88/100
800/800 [==============================] - 0s 613us/step - loss:

## Make Prediction 

In [30]:
# Predicts the probabilities
y_pred = classifier.predict(X_test)

In [31]:
y_pred

array([[0.33828723],
       [0.349397  ],
       [0.10723913],
       ...,
       [0.19748864],
       [0.13312331],
       [0.16476452]], dtype=float32)

In [32]:
# Predict the test results 
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [33]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)

In [35]:
cm

array([[1508,   87],
       [ 193,  212]])

In [36]:
acc = accuracy_score(y_test,y_pred)

In [37]:
acc

0.86

In [38]:
(1499+221)/(2000)

0.86

# Predict Single Entry

Use our ANN model to predict if the customer with the following informations will leave the bank:Â 

Geography: France 
Credit Score: 600 

Gender: Male\n
Age: 40 years old
Tenure: 3 years
Balance: $60000
Number of Products: 2
Does this customer have a credit card ? Yes
Is this customer an Active Member: Yes
Estimated Salary: $50000
So should we say goodbye to that customer ?

The solution is provided in the next Lecture but I strongly recommend that you try to solve it on your own.



In [69]:
new_prediction = classifier.predict(sc.fit_transform(np.array([[0,0,600,1,40,3,60000,2,1,1,50000]])))
new_prediction = (new_prediction > 0.5)

In [70]:
new_prediction

array([[False]])